---
- name: Disable root SSH login on RHEL
  hosts: all
  become: yes

  tasks:
    - name: Ensure root login is disabled in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service to apply changes
      systemd:
        name: sshd
        state: restarted
