---
- name: Create a file under /tmp
  hosts: all
  become: yes
  tasks:
    - name: Create /tmp/hello.txt with content
      copy:
        dest: /tmp/hello.txt
        content: "Hello from Ansible!\n"
        owner: root
        group: root
        mode: '0644'
